name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Résolution des dépendances via Swift Package Manager
    - name: Resolve dependencies
      run: swift package resolve

    # Build du projet
    - name: Build
      run: swift build -v

    # Exécution des tests
    - name: Run tests
      run: swift test -v
